version: '3.5'

networks:
  http_net:
  db_net:
  es_net:

volumes:
  cms-shared:
  dbdata:
  esdata:

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.1
    environment:
      - cluster.name=elastic-cluster
      - discovery.type=single-node
      - data
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xmx1G "
    #ports:
      #- 9200:9200
      #- 9600:9600
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - es_net

  dotcms:
    image: dotcms/dotcms:latest
    environment:
      "JAVA_OPTS_MEMORY": '-Xmx1g '
      "DB_BASE_URL": "jdbc:postgresql://db/dotcms"
      "DB_USERNAME": 'dotcmsdbuser'
      "DB_PASSWORD": 'password'
      "DOT_ES_ENDPOINTS": 'http://elasticsearch:9200'
      "DOT_ES_AUTH_BASIC_USER": 'admin'
      "DOT_ES_AUTH_BASIC_PASSWORD": 'admin'
      # "CUSTOM_STARTER_URL": 'https://repo.dotcms.com/artifactory/libs-release-local/com/dotcms/starter/20210903/starter-20210903.zip'
    depends_on:
      - elasticsearch
      - db
    volumes:
      - cms-shared:/data/shared
      #- [serverpath]/license.zip:/data/shared/assets/license.zip
    networks:
      - db_net
      - es_net
    ports:
      - "8080:8081"
      - "8443:8443"

  db:
    image: postgres:13
    command: postgres -c 'max_connections=400' -c 'shared_buffers=128MB'
    environment:
        "POSTGRES_USER": 'dotcmsdbuser'
        "POSTGRES_PASSWORD": 'password'
        "POSTGRES_DB": 'dotcms'
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - db_net
